{{- range $k, $v := .Values.imagePullSecrets }}
{{- if .create }}
apiVersion: v1
kind: Secret
metadata:
 name: {{ $k }}
data:
 .dockerconfigjson: {{ template "imagePullSecret" $v }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
