{{- if and .Values.service.enabled .Values.ports (gt (len .Values.ports) 0) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "general.fullname" . }}
  labels:
    {{- include "general.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $k, $v := .Values.ports }}
    - port: {{ $v.port }}
      targetPort: {{ $k | quote }}
      {{- if and $v.nodePort (eq $.Values.service.type "NodePort") }}
      nodePort: {{ $v.nodePort }}
      {{- end }}
      protocol: {{ $v.protocol | default "TCP" }}
      name: {{ $k | quote }}
    {{- end }}
  selector:
    {{- include "general.selectorLabels" . | nindent 4 }}
{{- end }}